service:
  kafka:
    enabled: true

kafka:
  bootstrap-servers: localhost:9092

server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auditdb  # MySQL connection
    username: root
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 50
        order_updates: true
        order_inserts: true
